server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/flowfall
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: ecfa4a4c6bdbd0
    password: dc54ae3a4ec438

security:
  allowedApis: /api/v1/auth/**,
               /api/v1/oauth2/**,
               /api/v1/webSocket/**
  oauth2:
    redirectUri: http://localhost:8080/api/v1/oauth2/token
    client:
      google:
        codeEndpoint: https://accounts.google.com/o/oauth2/auth
        tokenEndpoint: https://accounts.google.com/o/oauth2/token
        userInfoEndpoint: https://www.googleapis.com/oauth2/v1/userinfo
        clientId:
        clientSecret:
        scope: openid, profile, email
      facebook:
        codeEndpoint: https://www.facebook.com/dialog/oauth
        tokenEndpoint: https://graph.facebook.com/v2.4/oauth/access_token
        userInfoEndpoint: https://graph.facebook.com/me?fields=email,name,picture.type(large)
        clientId:
        clientSecret:
        scope: public_profile, email

water:
  apiUrl: http://localhost:8080/api/v1
  jwtExpiration: 86400
  jwtSecret: waterApiSecretCode
  jwtHeaderName: Authorization
  verificationTokenExpirationInMinutes: 1440
  supportEmail: flowfall@support.com
